// genfont.cpp - generates src/glyphs.hpp from a TrueType font.
//
// Rasterises printable ASCII plus the shogi piece kanji into anti-aliased
// 8-bit coverage bitmaps and emits a self-contained header, so the game keeps
// no font file or rasteriser at runtime (just like the old hand-coded font).
//
// Build & run:
//   c++ -O2 -Itools -o /tmp/genfont tools/genfont.cpp
//   /tmp/genfont tools/ShipporiMincho-Regular.ttf > src/glyphs.hpp
//
// Font used: Shippori Mincho (SIL OFL 1.1).  The OFL does not restrict the
// rendered *output* of a font, so the generated bitmaps - and this project -
// stay public domain.  The .ttf itself is not committed (see .gitignore);
// re-download it from the Google Fonts repository if regeneration is needed.
#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <vector>

int main(int argc, char** argv) {
  if (argc < 2) {
    std::fprintf(stderr, "usage: genfont FONT.ttf > glyphs.hpp\n");
    return 1;
  }
  FILE* f = std::fopen(argv[1], "rb");
  if (!f) { std::fprintf(stderr, "cannot open %s\n", argv[1]); return 1; }
  std::fseek(f, 0, SEEK_END);
  long n = std::ftell(f);
  std::fseek(f, 0, SEEK_SET);
  std::vector<unsigned char> font(n);
  if (std::fread(font.data(), 1, n, f) != size_t(n)) return 1;
  std::fclose(f);

  stbtt_fontinfo fi;
  if (!stbtt_InitFont(&fi, font.data(),
                      stbtt_GetFontOffsetForIndex(font.data(), 0))) {
    std::fprintf(stderr, "stbtt_InitFont failed\n");
    return 1;
  }

  const int ASCII_PX = 44, KANJI_PX = 52;
  // Shogi kanji, fixed order (see kanjiIndex() in ui.cpp):
  //   0 pawn  1 lance  2 knight  3 silver  4 gold  5 bishop  6 rook
  //   7 king(王)  8 king(玉)
  //   9 +pawn(と)  10 +lance(杏)  11 +knight(圭)  12 +silver(全)
  //   13 +bishop/horse(馬)  14 +rook/dragon(龍)
  const int kanji[] = {0x6B69, 0x9999, 0x6842, 0x9280, 0x91D1, 0x89D2, 0x98DB,
                       0x738B, 0x7389, 0x3068, 0x674F, 0x572D, 0x5168, 0x99AC,
                       0x9F8D};

  std::vector<unsigned char> pix;
  struct G { int w, h, xo, yo, adv; size_t off; };
  std::vector<G> ascii, kanjiG;

  auto render = [&](int px, int cp) -> G {
    float sc = stbtt_ScaleForPixelHeight(&fi, float(px));
    int w = 0, h = 0, xo = 0, yo = 0;
    unsigned char* bmp =
        stbtt_GetCodepointBitmap(&fi, sc, sc, cp, &w, &h, &xo, &yo);
    int adv = 0, lsb = 0;
    stbtt_GetCodepointHMetrics(&fi, cp, &adv, &lsb);
    G g{w, h, xo, yo, int(adv * sc + 0.5f), pix.size()};
    for (int i = 0; i < w * h; ++i) pix.push_back(bmp ? bmp[i] : 0);
    if (bmp) stbtt_FreeBitmap(bmp, nullptr);
    return g;
  };

  for (int c = 0x20; c <= 0x7E; ++c) ascii.push_back(render(ASCII_PX, c));
  for (int cp : kanji) kanjiG.push_back(render(KANJI_PX, cp));

  int asc = 0, desc = 0, gap = 0;
  stbtt_GetFontVMetrics(&fi, &asc, &desc, &gap);
  int asciiAscent =
      int(asc * stbtt_ScaleForPixelHeight(&fi, float(ASCII_PX)) + 0.5f);

  std::printf("// glyphs.hpp - GENERATED by tools/genfont.cpp.  Do not edit.\n");
  std::printf("// Anti-aliased coverage bitmaps: printable ASCII + shogi"
              " kanji,\n// rasterised from Shippori Mincho.\n");
  std::printf("#pragma once\n#include <cstdint>\n\nnamespace shogi {\n\n");
  std::printf("struct GlyphInfo { int16_t w, h, xoff, yoff, advance;"
              " uint32_t pix; };\n\n");
  std::printf("constexpr int ASCII_PX     = %d;  // design pixel height\n",
              ASCII_PX);
  std::printf("constexpr int ASCII_ASCENT = %d;  // baseline below the top\n",
              asciiAscent);
  std::printf("constexpr int KANJI_PX     = %d;\n\n", KANJI_PX);

  auto emit = [](const char* name, const std::vector<G>& v) {
    std::printf("inline const GlyphInfo %s[%zu] = {\n", name, v.size());
    for (const G& g : v)
      std::printf("  {%d,%d,%d,%d,%d,%zu},\n", g.w, g.h, g.xo, g.yo, g.adv,
                  g.off);
    std::printf("};\n\n");
  };
  emit("ASCII_GLYPHS", ascii);   // index by codepoint - 0x20
  emit("KANJI_GLYPHS", kanjiG);

  std::printf("inline const uint8_t GLYPH_PIX[%zu] = {\n", pix.size());
  for (size_t i = 0; i < pix.size(); ++i) {
    std::printf("%u,", pix[i]);
    if ((i & 31) == 31) std::printf("\n");
  }
  std::printf("\n};\n\n}  // namespace shogi\n");
  return 0;
}
