// genfont.cpp - generates src/glyphs.hpp from two TrueType fonts.
//
// Rasterises printable ASCII (from a sans font) and the shogi piece kanji
// (from a Mincho font) into anti-aliased 8-bit coverage bitmaps and emits a
// self-contained header, so the game keeps no font file or rasteriser at
// runtime (just like the old hand-coded font).
//
// Build & run:
//   c++ -O2 -Itools -o /tmp/genfont tools/genfont.cpp
//   /tmp/genfont tools/NotoSans.ttf tools/ShipporiMincho-Regular.ttf \
//       > src/glyphs.hpp
//
// Fonts: Noto Sans (OFL) for the UI Latin text, Shippori Mincho (OFL) for the
// piece kanji.  The OFL does not restrict the rendered *output* of a font, so
// the generated bitmaps - and this project - stay public domain.  The .ttf
// files are not committed (see .gitignore); re-download them from the Google
// Fonts repository if regeneration is needed.
#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <vector>

static std::vector<unsigned char> readFile(const char* path) {
  FILE* f = std::fopen(path, "rb");
  if (!f) { std::fprintf(stderr, "cannot open %s\n", path); std::exit(1); }
  std::fseek(f, 0, SEEK_END);
  long n = std::ftell(f);
  std::fseek(f, 0, SEEK_SET);
  std::vector<unsigned char> buf(n);
  if (std::fread(buf.data(), 1, n, f) != size_t(n)) std::exit(1);
  std::fclose(f);
  return buf;
}

int main(int argc, char** argv) {
  if (argc < 3) {
    std::fprintf(stderr, "usage: genfont SANS.ttf KANJI.ttf > glyphs.hpp\n");
    return 1;
  }
  std::vector<unsigned char> sansData = readFile(argv[1]);
  std::vector<unsigned char> kanjiData = readFile(argv[2]);
  stbtt_fontinfo sans, mincho;
  if (!stbtt_InitFont(&sans, sansData.data(),
                      stbtt_GetFontOffsetForIndex(sansData.data(), 0)) ||
      !stbtt_InitFont(&mincho, kanjiData.data(),
                      stbtt_GetFontOffsetForIndex(kanjiData.data(), 0))) {
    std::fprintf(stderr, "stbtt_InitFont failed\n");
    return 1;
  }

  const int ASCII_PX = 60, KANJI_PX = 60;
  // Shogi kanji, fixed order (see kanjiIndex() in ui.cpp):
  //   0 pawn  1 lance  2 knight  3 silver  4 gold  5 bishop  6 rook
  //   7 king(王)  8 king(玉)
  //   9 +pawn(と)  10 +lance(杏)  11 +knight(圭)  12 +silver(全)
  //   13 +bishop/horse(馬)  14 +rook/dragon(龍)
  const int kanji[] = {0x6B69, 0x9999, 0x6842, 0x9280, 0x91D1, 0x89D2, 0x98DB,
                       0x738B, 0x7389, 0x3068, 0x674F, 0x572D, 0x5168, 0x99AC,
                       0x9F8D};

  std::vector<unsigned char> pix;
  struct G { int w, h, xo, yo, adv; size_t off; };
  std::vector<G> ascii, kanjiG;

  auto render = [&](stbtt_fontinfo& fi, int px, int cp) -> G {
    float sc = stbtt_ScaleForPixelHeight(&fi, float(px));
    int w = 0, h = 0, xo = 0, yo = 0;
    unsigned char* bmp =
        stbtt_GetCodepointBitmap(&fi, sc, sc, cp, &w, &h, &xo, &yo);
    int adv = 0, lsb = 0;
    stbtt_GetCodepointHMetrics(&fi, cp, &adv, &lsb);
    G g{w, h, xo, yo, int(adv * sc + 0.5f), pix.size()};
    for (int i = 0; i < w * h; ++i) pix.push_back(bmp ? bmp[i] : 0);
    if (bmp) stbtt_FreeBitmap(bmp, nullptr);
    return g;
  };

  for (int c = 0x20; c <= 0x7E; ++c) ascii.push_back(render(sans, ASCII_PX, c));
  for (int cp : kanji) kanjiG.push_back(render(mincho, KANJI_PX, cp));

  int asc = 0, desc = 0, gap = 0;
  stbtt_GetFontVMetrics(&sans, &asc, &desc, &gap);
  int asciiAscent =
      int(asc * stbtt_ScaleForPixelHeight(&sans, float(ASCII_PX)) + 0.5f);

  std::printf("// glyphs.hpp - GENERATED by tools/genfont.cpp.  Do not edit.\n");
  std::printf("// Anti-aliased coverage bitmaps: printable ASCII (Noto Sans)\n");
  std::printf("// and the shogi piece kanji (Shippori Mincho).\n");
  std::printf("#pragma once\n#include <cstdint>\n\nnamespace shogi {\n\n");
  std::printf("struct GlyphInfo { int16_t w, h, xoff, yoff, advance;"
              " uint32_t pix; };\n\n");
  std::printf("constexpr int ASCII_PX     = %d;  // design pixel height\n",
              ASCII_PX);
  std::printf("constexpr int ASCII_ASCENT = %d;  // baseline below the top\n",
              asciiAscent);
  std::printf("constexpr int KANJI_PX     = %d;\n\n", KANJI_PX);

  auto emit = [](const char* name, const std::vector<G>& v) {
    std::printf("inline const GlyphInfo %s[%zu] = {\n", name, v.size());
    for (const G& g : v)
      std::printf("  {%d,%d,%d,%d,%d,%zu},\n", g.w, g.h, g.xo, g.yo, g.adv,
                  g.off);
    std::printf("};\n\n");
  };
  emit("ASCII_GLYPHS", ascii);   // index by codepoint - 0x20
  emit("KANJI_GLYPHS", kanjiG);

  std::printf("inline const uint8_t GLYPH_PIX[%zu] = {\n", pix.size());
  for (size_t i = 0; i < pix.size(); ++i) {
    std::printf("%u,", pix[i]);
    if ((i & 31) == 31) std::printf("\n");
  }
  std::printf("\n};\n\n}  // namespace shogi\n");
  return 0;
}
